# Generated by Django 2.2 on 2019-06-23 10:19

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='grades_file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_homework_grades_to),
        ),
    ]
