# Generated by Django 2.2 on 2019-06-29 14:34

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_name',
            field=models.CharField(default='undefined', max_length=100),
        ),
        migrations.AddField(
            model_name='section',
            name='enroll_key',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='grades_file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_homework_grades_to),
        ),
        migrations.AlterField(
            model_name='homework',
            name='solution_file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_homework_solution_to),
        ),
    ]
