# Generated by Django 2.2 on 2019-06-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190623_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='sender_name',
            field=models.CharField(default='undefined', max_length=50),
        ),
    ]
